[package]
name = "rdm2"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
borsh = "1.5.7"
serde_json = "1.0.140"
solana-client = "2.3.2"
solana-sdk = "2.3.1"
spl-associated-token-account = "7.0.0"
spl-memo = "6.0.0"
spl-token = "8.0.0"
